services:
   bank_database:
      container_name: bank_database
      image: mariadb:latest
      restart: unless-stopped
      environment:
         MARIADB_ROOT_PASSWORD: rootpassword
         MARIADB_DATABASE: bank
         MARIADB_USER: banker
         MARIADB_PASSWORD: mypassword
      ports:
         - '3306:3306'
      volumes:
         - database_data:/var/lib/mysql
         - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
   bank_api:
      container_name: bank
      image: node:latest
      restart: unless-stopped
      working_dir: /app/src
      volumes:
         - ./:/app/src
      depends_on:
         - bank_database
      ports:
         - '3000:3000'
      command: './run.sh'

volumes:
   database_data: